/* Lightweight birthday interactions */

(() => {
  const $ = (s) => document.querySelector(s);
  const opening=$("#opening"),welcome=$("#welcomeName"),heroName=$("#heroName"),savedName=localStorage.getItem("birthdayLoginName");
  if(savedName){if(welcome)welcome.textContent=`Welcome, ${savedName}. Your birthday universe is ready. 💗`;if(heroName)heroName.textContent=`${savedName}.`;}
  function showOpening(){if(!opening)return;opening.classList.remove("show");void opening.offsetWidth;opening.classList.add("show");}
  $("#unlockBtn")?.addEventListener("click",()=>setTimeout(showOpening,20));$("#loginForm")?.addEventListener("submit",()=>setTimeout(showOpening,20));
  const deck=$("#deck");if(deck){[...deck.querySelectorAll(".deck-card")].slice(3).forEach(c=>c.remove());const count=document.querySelector(".album-count");if(count)count.innerHTML='<span id="albumIndex">01</span> / 03';}

  /* MINI GAME 01 — Birthday Runner */
  const area=$("#gameArea"),start=$("#gameStart"),scoreText=$("#gameScore"),rankText=$("#gameRank"),bestText=$("#gameBest"),result=$("#gameResult"),player=$("#runnerPlayer"),obstacle=$("#runnerObstacle"),bird=$("#runnerBird"),startHint=$("#runnerStartHint"),gameOver=$("#runnerGameOver"),finalScore=$("#runnerFinalScore");
  const ranks=[{min:0,name:"Rookie",badge:"🌱",title:"Awal yang bagus!",message:"Pemanasan selesai. Terus latihan dan kejar Master!"},{min:1000,name:"Master",badge:"🏆",title:"MASTER UNLOCKED!",message:"1000 poin! Refleksmu mulai nggak main-main!"},{min:2000,name:"Grand Master",badge:"👑",title:"GRAND MASTER!",message:"2000 poin! Kamu sudah masuk kelas pemain serius."},{min:3000,name:"Legend",badge:"⚡",title:"LEGENDARY RUN!",message:"3000 poin! Lari sejauh ini bukan kebetulan."},{min:4000,name:"Mythic",badge:"💎",title:"MYTHIC!",message:"4000 poin! Ini sudah level yang susah dipercaya."},{min:5000,name:"Immortal",badge:"🔥",title:"IMMORTAL!",message:"5000 poin! Kamu benar-benar bertahan sejauh ini."},{min:6000,name:"Supreme",badge:"🌟",title:"SUPREME RUNNER!",message:"6000 poin! Rank tertinggi tercapai. Respect!"}];
  const getRank=v=>ranks.reduce((a,r)=>v>=r.min?r:a,ranks[0]),getNextRank=v=>ranks.find(r=>r.min>v)||null;
  const achievementModal=$("#achievementModal"),achievementClose=$("#achievementClose"),achievementRestart=$("#achievementRestart"),achievementBadge=$("#achievementBadge"),achievementTitle=$("#achievementTitle"),achievementRank=$("#achievementRank"),achievementScore=$("#achievementScore"),achievementMessage=$("#achievementMessage"),achievementNext=$("#achievementNext");
  let running=false,animation=0,last=0,score=0,best=Number(localStorage.getItem("birthdayRunnerBest")||0),playerY=0,velocity=0,obstacleX=0,obstacleSpeed=210,birdX=0,birdY=55;
  if(bestText)bestText.textContent=best;if(rankText)rankText.textContent=getRank(best).name;
  function setVisuals(){if(!area)return;if(player)player.style.transform=`translate3d(0,${-playerY}px,0)`;if(obstacle)obstacle.style.transform=`translate3d(${obstacleX}px,0,0)`;if(bird)bird.style.transform=`translate3d(${birdX}px,${-birdY}px,0)`;}
  function resetRunner(){if(!area)return;score=0;playerY=0;velocity=0;obstacleSpeed=210;obstacleX=area.clientWidth+100;birdX=area.clientWidth+380;birdY=55;setVisuals();if(scoreText)scoreText.textContent="0";if(rankText)rankText.textContent="Rookie";}
  function jump(){if(running&&playerY<=2)velocity=620;}
  function hitTest(){const ground=area.clientHeight-32,pL=42,pR=pL+34,pB=ground-playerY,pT=pB-38,oL=obstacleX+7,oR=oL+30,oB=ground,oT=oB-35;return oL<pR&&oR>pL&&pB>oT+5&&pT<oB-2;}
  function showAchievement(value){const c=getRank(value),n=getNextRank(value);if(achievementBadge)achievementBadge.textContent=c.badge;if(achievementTitle)achievementTitle.textContent=c.title;if(achievementRank)achievementRank.textContent=c.name;if(achievementScore)achievementScore.textContent=value;if(achievementMessage)achievementMessage.textContent=c.message;if(achievementNext)achievementNext.textContent=n?`${n.name} · ${n.min}`:"MAX RANK · Supreme";achievementModal?.classList.add("show");achievementModal?.setAttribute("aria-hidden","false");}
  function hideAchievement(){achievementModal?.classList.remove("show");achievementModal?.setAttribute("aria-hidden","true");}
  function endGame(){running=false;cancelAnimationFrame(animation);const value=Math.floor(score),c=getRank(value);if(finalScore)finalScore.textContent=value;if(rankText)rankText.textContent=c.name;if(value>best){best=value;localStorage.setItem("birthdayRunnerBest",String(best));if(bestText)bestText.textContent=best;}if(gameOver)gameOver.hidden=false;if(startHint)startHint.hidden=true;if(start){start.disabled=false;start.textContent="Main lagi ↻";}if(result)result.textContent=`Kalah! Score ${value} · Rank ${c.name}. Lihat pencapaianmu di bawah. 🏆`;showAchievement(value);}
  function frame(now){if(!running)return;const dt=Math.min((now-last)/1000,.032);last=now;velocity-=1650*dt;playerY+=velocity*dt;if(playerY<0){playerY=0;velocity=0;}score+=dt*10;
    if(score<1000)obstacleSpeed=210+(score/1000)*20;else if(score<2000)obstacleSpeed=230+((score-1000)/1000)*35;else if(score<3000)obstacleSpeed=265+((score-2000)/1000)*45;else if(score<4000)obstacleSpeed=310+((score-3000)/1000)*45;else if(score<5000)obstacleSpeed=355+((score-4000)/1000)*45;else if(score<6000)obstacleSpeed=400+((score-5000)/1000)*260;else obstacleSpeed=660;
    obstacleX-=obstacleSpeed*dt;if(obstacleX<-75)obstacleX=area.clientWidth+100;
    if(score>=1000){const birdSpeed=Math.min(600,185+(score-1000)*.075);birdX-=birdSpeed*dt;birdY=55+Math.sin(now/220)*8;if(birdX<-70)birdX=area.clientWidth+330+Math.random()*180;}else{birdX=area.clientWidth+380;birdY=55;}
    const c=getRank(score);setVisuals();if(scoreText)scoreText.textContent=String(Math.floor(score));if(rankText)rankText.textContent=c.name;if(hitTest()){endGame();return;}animation=requestAnimationFrame(frame);}
  function startRunner(){if(!area)return;hideAchievement();cancelAnimationFrame(animation);resetRunner();running=true;last=performance.now();if(gameOver)gameOver.hidden=true;if(startHint)startHint.hidden=true;if(start){start.disabled=true;start.textContent="Runner berjalan...";}if(result)result.textContent="Lompatin 🎁 dan perhatikan 🐦! Burung muncul mulai 1000 poin.";area.focus({preventScroll:true});animation=requestAnimationFrame(frame);}
  start?.addEventListener("click",startRunner);achievementRestart?.addEventListener("click",startRunner);achievementClose?.addEventListener("click",hideAchievement);achievementModal?.addEventListener("click",e=>{if(e.target===achievementModal)hideAchievement();});
  area?.addEventListener("pointerdown",e=>{e.preventDefault();if(running)jump();else if(start&&!start.disabled)startRunner();});
  document.addEventListener("keydown",e=>{if(e.code!=="Space")return;if(!running&&document.activeElement!==area)return;e.preventDefault();if(running)jump();});
  area?.addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();jump();}});resetRunner();

  /* MINI GAME 02 — Sky Battle */
  const airArea=$("#airGameArea"),airStart=$("#airStart"),airPlayer=$("#airPlayer"),airEnemies=$("#airEnemies"),airBullets=$("#airBullets"),airEnemyBullets=$("#airEnemyBullets"),airMedkits=$("#airMedkits"),airHpText=$("#airHp"),airScoreText=$("#airScore"),airBestText=$("#airBest"),airHint=$("#airStartHint"),airOver=$("#airGameOver"),airFinal=$("#airFinalScore"),airResult=$("#airResult");
  let airRunning=false,airAnim=0,airLast=0,airScore=0,airHp=5,airBest=Number(localStorage.getItem("skyBattleBest")||0),airX=0,airEnemyId=0,airShotTimer=0,airEnemyShotTimer=0,airMedTimer=0,airSpawnTimer=0,airBulletsData=[],airEnemyBulletsData=[],airEnemiesData=[],airMedkitsData=[];
  if(airBestText)airBestText.textContent=airBest;if(airHpText)airHpText.textContent=airHp;
  function clearAir(){airEnemiesData=[];airBulletsData=[];airEnemyBulletsData=[];airMedkitsData=[];airEnemies.innerHTML="";airBullets.innerHTML="";airEnemyBullets.innerHTML="";airMedkits.innerHTML="";}
  function resetAir(){if(!airArea)return;airScore=0;airHp=5;airX=Math.max(0,airArea.clientWidth/2-24);airShotTimer=0;airEnemyShotTimer=0;airMedTimer=0;airSpawnTimer=.2;clearAir();airPlayer.style.left=`${airX}px`;airPlayer.style.transform="none";if(airHpText)airHpText.textContent="5";if(airScoreText)airScoreText.textContent="0";}
  function makeAirEl(parent,cls,text){const el=document.createElement("div");el.className=cls;el.textContent=text;parent.appendChild(el);return el;}
  function spawnEnemy(){const x=10+Math.random()*Math.max(10,airArea.clientWidth-60),el=makeAirEl(airEnemies,"air-enemy",Math.random()<.5?"🛩️":"🚁");airEnemiesData.push({id:++airEnemyId,x,y:-45,speed:45+Math.random()*35,el,shot:Math.random()*.7});el.style.transform=`translate3d(${x}px,${-45}px,0)`;}
  function spawnMedkit(){const x=12+Math.random()*Math.max(12,airArea.clientWidth-42),el=makeAirEl(airMedkits,"air-medkit","❤️");airMedkitsData.push({x,y:-35,speed:55,el});el.style.transform=`translate3d(${x}px,-35px,0)`;}
  function firePlayer(){const x=airX+20,y=airArea.clientHeight-65,el=makeAirEl(airBullets,"air-bullet","");airBulletsData.push({x,y,speed:360,el});el.style.transform=`translate3d(${x}px,${y}px,0)`;}
  function fireEnemy(e){const x=e.x+17,y=e.y+30,el=makeAirEl(airEnemyBullets,"air-enemy-bullet","");airEnemyBulletsData.push({x,y,speed:150,el});el.style.transform=`translate3d(${x}px,${y}px,0)`;}
  function overlaps(a,b,w,h){return a.x<b.x+w&&a.x+8>b.x&&a.y<b.y+h&&a.y+18>b.y;}
  function airHit(){airHp--;if(airHpText)airHpText.textContent=airHp;if(airHp<=0)endAir();}
  function endAir(){airRunning=false;cancelAnimationFrame(airAnim);const v=Math.floor(airScore);if(v>airBest){airBest=v;localStorage.setItem("skyBattleBest",String(v));if(airBestText)airBestText.textContent=v;}if(airFinal)airFinal.textContent=v;if(airOver)airOver.hidden=false;if(airHint)airHint.hidden=true;if(airStart){airStart.disabled=false;airStart.textContent="Main lagi ↻";}if(airResult)airResult.textContent=`Game over! Score ${v} · HP habis. Coba lagi dan bertahan lebih lama.`;}
  function updateAirVisuals(){airPlayer.style.left=`${airX}px`;}
  function airFrame(now){if(!airRunning)return;const dt=Math.min((now-airLast)/1000,.032);airLast=now;airScore+=dt*12;airShotTimer+=dt;airEnemyShotTimer+=dt;airMedTimer+=dt;airSpawnTimer+=dt;
    const difficulty=1+Math.min(1.5,airScore/2500);if(airShotTimer>.38){airShotTimer=0;firePlayer();}if(airSpawnTimer>Math.max(.48,1.15-airScore*.00012)){airSpawnTimer=0;spawnEnemy();}if(airMedTimer>12){airMedTimer=0;if(Math.random()<.8)spawnMedkit();}
    airEnemiesData.forEach(e=>{e.y+=e.speed*difficulty*dt;e.shot+=dt;if(e.shot>.95/difficulty){e.shot=0;fireEnemy(e);}e.el.style.transform=`translate3d(${e.x}px,${e.y}px,0)`;});
    airBulletsData.forEach(b=>{b.y-=b.speed*dt;b.el.style.transform=`translate3d(${b.x}px,${b.y}px,0)`;});airEnemyBulletsData.forEach(b=>{b.y+=b.speed*difficulty*dt;b.el.style.transform=`translate3d(${b.x}px,${b.y}px,0)`;});airMedkitsData.forEach(m=>{m.y+=m.speed*dt;m.el.style.transform=`translate3d(${m.x}px,${m.y}px,0)`;});
    for(let i=airBulletsData.length-1;i>=0;i--){const b=airBulletsData[i];let hit=false;for(let j=airEnemiesData.length-1;j>=0;j--){const e=airEnemiesData[j];if(overlaps(b,e,38,36)){e.el.remove();airEnemiesData.splice(j,1);b.el.remove();airBulletsData.splice(i,1);airScore+=35;hit=true;break;}}if(!hit&&b.y<-25){b.el.remove();airBulletsData.splice(i,1);}}
    for(let i=airEnemyBulletsData.length-1;i>=0;i--){const b=airEnemyBulletsData[i];if(overlaps(b,{x:airX,y:airArea.clientHeight-65},48,48)){b.el.remove();airEnemyBulletsData.splice(i,1);airHit();if(!airRunning)return;}else if(b.y>airArea.clientHeight+20){b.el.remove();airEnemyBulletsData.splice(i,1);}}
    for(let i=airMedkitsData.length-1;i>=0;i--){const m=airMedkitsData[i];if(m.y>airArea.clientHeight+30){m.el.remove();airMedkitsData.splice(i,1);}else if(overlaps({x:m.x,y:m.y}, {x:airX,y:airArea.clientHeight-65},48,48)){airHp=Math.min(5,airHp+1);if(airHpText)airHpText.textContent=airHp;m.el.remove();airMedkitsData.splice(i,1);}}
    for(let i=airEnemiesData.length-1;i>=0;i--){const e=airEnemiesData[i];if(e.y>airArea.clientHeight+20){e.el.remove();airEnemiesData.splice(i,1);}else if(overlaps({x:e.x,y:e.y},{x:airX,y:airArea.clientHeight-65},48,48)){e.el.remove();airEnemiesData.splice(i,1);airHit();if(!airRunning)return;}}
    if(airScoreText)airScoreText.textContent=String(Math.floor(airScore));updateAirVisuals();airAnim=requestAnimationFrame(airFrame);}
  function startAir(){if(!airArea)return;cancelAnimationFrame(airAnim);resetAir();airRunning=true;airLast=performance.now();if(airOver)airOver.hidden=true;if(airHint)airHint.hidden=true;if(airStart){airStart.disabled=true;airStart.textContent="Sky Battle berjalan...";}if(airResult)airResult.textContent="Tembakan otomatis. Geser pesawat, hindari peluru, ambil ❤️ untuk tambah HP.";airArea.focus({preventScroll:true});airAnim=requestAnimationFrame(airFrame);}
  function moveAir(clientX){if(!airRunning)return;const r=airArea.getBoundingClientRect();airX=Math.max(0,Math.min(airArea.clientWidth-48,clientX-r.left-24));updateAirVisuals();}
  airStart?.addEventListener("click",startAir);airArea?.addEventListener("pointerdown",e=>{e.preventDefault();if(!airRunning){startAir();}moveAir(e.clientX);airArea.setPointerCapture?.(e.pointerId);});airArea?.addEventListener("pointermove",e=>{if(airRunning)moveAir(e.clientX);});

  /* MINI GAME SLIDER — swipe left/right */
  const slider=$("#miniGameSlider"),track=slider?.querySelector(".mini-game-track"),dots=[...document.querySelectorAll(".mini-dot")];let slideIndex=0,slideStartX=0,slideDragging=false;
  function goSlide(i){if(!track)return;slideIndex=Math.max(0,Math.min(1,i));track.style.transform=`translate3d(${-slideIndex*100}%,0,0)`;dots.forEach((d,n)=>d.classList.toggle("active",n===slideIndex));}
  dots.forEach(d=>d.addEventListener("click",()=>goSlide(Number(d.dataset.gameSlide))));
  slider?.addEventListener("pointerdown",e=>{slideStartX=e.clientX;slideDragging=true;});
  slider?.addEventListener("pointerup",e=>{if(!slideDragging)return;slideDragging=false;const dx=e.clientX-slideStartX;if(Math.abs(dx)>45)goSlide(slideIndex+(dx<0?1:-1));});
  slider?.addEventListener("pointercancel",()=>slideDragging=false);goSlide(0);

  const letterBtn=$("#letterBtn"),letterContent=$("#letterContent");letterBtn?.addEventListener("click",()=>{const open=letterContent.classList.toggle("open");letterBtn.setAttribute("aria-expanded",String(open));letterContent.setAttribute("aria-hidden",String(!open));const hint=letterBtn.querySelector("small");if(hint)hint.textContent=open?"Tap to close":"Tap to open";});
  const finalBtn=$("#finalBtn"),finalMessage=$("#finalMessage");finalBtn?.addEventListener("click",()=>{const open=finalMessage.classList.toggle("show");finalMessage.setAttribute("aria-hidden",String(!open));finalBtn.textContent=open?"Close surprise ✨":"Open the last surprise 🎁";if(open){const burst=document.createElement("div");burst.className="final-burst";burst.textContent="🎉 ✨ 🎈 💗 🎂";finalMessage.appendChild(burst);setTimeout(()=>burst.remove(),1800);}});
})();
